### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by tylergale** [maxandersen/internet-monitoring#11]
Hello!

I have followed the instructions as provided in the readme, and have done a fresh install on a fresh Ubuntu server instance with latest docker and docker compose.

Upon executing the docker-compose, everything goes just fine and I am able to bring up the prometheus dashboards, but alas, all graphs are empty and have a small "exclamation mark" on each of them saying "Method not allowed" which I assume is why the graph is not being filled out.

As an example (speedtest ping graph) when clicking the exclamation mark and checking out the query:
{
  "request": {
    "url": "api/datasources/proxy/1/api/v1/query_range",
    "method": "POST",
    "data": {
      "query": "speedtest_ping",
      "start": 1626570540,
      "end": 1626570840,
      "step": 15
    },
    "hideFromInspector": false
  },
  "response": {
    "error": "Method Not Allowed",
    "response": "Method Not Allowed\n",
    "message": "Method Not Allowed\n"
  }
}

Have I done something wrong, or has something changed?

**Comment by tylergale** [comment]
Additional info!

I have checked the targets and status links and can see that the tests are being run properly, and prometheus is well aware of it too, but for whatever reason the graphs are just not populating due to the "Method not allowed" error

**Comment by kitdavis** [comment]
I have the same issue - I have had a working configuration for months.   Created a new Ubuntu 18.04 server, ran the install and got all of the charts with the Method not Allowed message.   Created a new Debian server and have the same problem there as well.

**Comment by KRSogaard** [comment]
Same issue here, i am running it in windows 10

**Comment by MyFilippo94** [comment]
Same here, running it in a test VM Ubuntu server.
