### ISSUE TITLE
Adhere to upstream's new license

### ISSUE THREAD

**Issue by ItsDrike** [maxandersen/internet-monitoring#17]
The project this repository is based on just added an MIT license as a response to [this issue](https://github.com/vegasbrianc/github-monitoring/issues/20)

You should adhere to this and merge it into this project from upstream (original repo which this project is forked from). Not following a license is considered illegal as it breaks the copyright law (read more in the linked issue).

Since MIT is a permissive license, you can also relicense under a different license in case you wouldn't want to use MIT (as long as you follow the terms of MIT and give proper attributions).

**Comment by maxandersen** [comment]
I do not see how "Not follwing a license is considered illegal" as this was forked long time before that license was added and no rebasing relevant for this.

happy to see pullrequest updating/adding license but closing this specific issue as not relevant.

**Comment by ItsDrike** [comment]
The problem is that no license doesn't mean no legal restrictions when forking, it's actually the other way around.

The license is the only thing giving the contributors a right to utilize that code, if there's no license, normal copyright law applies. Authors don't need to "add" a copyright to their code, they gain it automatically, just like with any other creative work (i.e. for paintings). The software license is then just the author giving us something to extend that copyright, which would allow others to use it.

When this fork was created from an unlicensed repo, you were already in the wrong legally, you never had the right to create this work in the first place. Now that a license was added on the upstream, this issue is finally fixed, but you need to actually adhere to it.

To be fair, to follow the upstream's new MIT license, you don't actually need to license this repo under MIT too, MIT is permissive and allows sublicensing or even closed repositories, however if you won't add some form of a license here, every contributor using this code, or forking it is breaking the copyright law, because you didn't give us the permission to actually use your code.

If you want to know some more about this, you can read [this post on my webpage](https://itsdrike.com/posts/software-licenses/), fair warning though, it is pretty long and complex, but you don't need to read most of it, just going over the "How are licenses enforced" section" should be enough if you want to understand this a bit more.
