### ISSUE TITLE
Add Grafana password to readme file

### ISSUE THREAD

**Issue by Quinten0508** [maxandersen/internet-monitoring#21]
Might be a good idea to add the login credentials for the grafana dashboard to your readme/installation instructions:
username: `admin`
password: `wonka`

**Comment by Quinten0508** [comment]
to clarify: add it to the quick-start guide section.

**Comment by maxandersen** [comment]
PRs welcome

**Comment by Quinten0508** [comment]
Commented on the other open issue for a possible PR.
Issue closed.

**Comment by dexteon** [comment]
LOL thank you for posting this.
